config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'feed' => 'epicenter#feed'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  post 'epi_tweet' => 'epicenter#epi_tweet'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  get 'all_users' => 'epicenter#all_users'

  get 'following' => 'epicenter#following'

  get 'followers' => 'epicenter#followers'

  get 'trending' => 'epicenter#trending'

  resources :tweets
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord

	belongs_to :user

	has_many :tweet_tags
	has_many :tags, through: :tweet_tags

	before_validation :link_check, on: :create

	validates :message, presence: true, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows that!"}, on: :create

	after_validation :apply_link, on: :create

	private

	  def link_check
		  check = false
		  if self.message.include?("http://") || self.message.include?("https://") || self.message.include?("www.")
		    	check = true
		  end

		  if check == true
				arr = self.message.split
				index = arr.map{|x| x.include?("http") || x.include?("www.")}.index(true)
		    self.link = arr[index]
		    if arr[index].length > 23
			    arr[index] = "#{arr[index][0..20]}..."	
		    end
						
		    self.message = arr.join(" ")
		  end
	  end

	  def apply_link
			arr = self.message.split
			index = arr.map {|x| x.include?("http://") || x.include?("https://") || x.include?("www.")}.index(true)

			if index
				url = arr[index]
				if arr[index][0] == "w"
					arr[index] = "<a href='http://#{self.link}' target='_blank'>#{url}</a>"
				else
					arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
				end
			end

			self.message = arr.join(" ")
		end

end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
	belongs_to :tweet
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets

  mount_uploader :avatar, AvatarUploader

  validates :username, presence: true, uniqueness: true
  validates :avatar, presence: true
  validates :email, presence: true, uniqueness: true

  serialize :following, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar, :following])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

	before_action :authenticate_user!
  include TweetsHelper
  include EpicenterHelper
	
  def feed
    @tweet = Tweet.new
    @following_tweets = []

    Tweet.order(created_at: :desc).each do |tweet|
      if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
        @following_tweets.push(tweet)
      end
    end

	end

  def show_user
    @tweet = Tweet.new
  	@user = User.find(params[:id])
    @followers = number_of_followers(@user)
  end

  def all_users
    @users = User.order(:username)
  end

  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
    end

  end

  def followers
    @user =  User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end
    
  end

  def now_following
  	current_user.following.push(params[:id].to_i)
	  current_user.save

	  redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    current_user.following.delete(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def epi_tweet
    @tweet = Tweet.create(message: params[:tweet][:message], user_id: params[:tweet][:user_id])

    @tweet = get_tagged(@tweet)
    @tweet.save
    
    redirect_to root_path
  end

  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  def trending
    # Hash of top 3 tweeters
    @tweet_hash = Tweet.group(:user_id).order('count_id desc').limit(3).count(:id)
    # Hash of top 3 tags
    @tweet_tag_hash = TweetTag.group(:tag_id).order('count_id desc').limit(3).count(:id)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.order(created_at: :desc)
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)
    
    @tweet = get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper

	def number_of_followers(user)
		followers = 0
		
		User.all.each do |x|
			if x.following.include?(user.id)
				followers += 1
			end
		end

		return followers
	end

end

app/helpers/tweets_helper.rb
module TweetsHelper
	def get_tagged(tweet)
		message_arr = tweet.message.split

    message_arr.each_with_index do |word, index|
      if word[0] == "#"
        if Tag.pluck(:phrase).include?(word.downcase)
          tag = Tag.find_by(phrase: word.downcase)
        else
          tag = Tag.create(phrase: word.downcase)
        end
        tweet_tag = TweetTag.create(tweet_id: @tweet.id, tag_id: tag.id)
        message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
      end
    end

    tweet.message = message_arr.join(" ")
    return tweet
	end
end

app/views/epicenter/_newtweet.html.erb
<%= form_for @tweet, url: {action: "epi_tweet"} do |f| %>
	<%= f.text_area :message, placeholder: "Got something to say?", class: "form-control", rows: 4 %>
	<%= f.hidden_field :user_id, value: current_user.id %>
	<div class="text-center" style="margin-top: 10px">
		<%= f.submit "Tweet it!", class: "btn btn-primary" %>
	</div>
<% end %>

app/views/epicenter/_user_list.html.erb
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<% @users.each do |user| %>
			<div class="card">
				<div class="card-body">
					<div class="media">
					  <%= image_tag user.avatar_url(:thumb), class: "rounded-circle", style: "margin-right: 10px" %>
					  <div class="media-body">
						    <p>
						    	<%= user.name %> @<%= link_to user.username, show_user_path(id: user.id) %>
						    </p>
						    <p class="card-text">
						    	Name: <%= user.name %> | Location: <%= user.location %>
					    	</p>
					  </div>
					</div>
				</div>
			  <% if current_user.following.include?(user.id) %>
		      <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary unfollow-btn" %>
		    <% elsif current_user.id != user.id %>
		      <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
		    <% end %>
			</div>
			<br>
		<% end %>
	</div>
	<div class="col-md-3"></div>
</div>

app/views/epicenter/all_users.html.erb
<br>
<h3 class="text-center">All Users on the Street</h3>
<br>

<%= render 'user_list' %>

<div class="text-center">
	<%= link_to "Feed", feed_path, class: "btn btn-primary" %>
</div>
<br>

app/views/epicenter/feed.html.erb
<br>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<%= render 'epicenter/newtweet' %>
		<hr>
	  <% @following_tweets.each do |tweet| %>
	  	<div class="card">
			  <div class="card-body">
			  	<div class="media">
					  <%= image_tag tweet.user.avatar_url(:thumb), class: "rounded-circle", style: "margin-right: 10px" %>
					  <div class="media-body">
						    <p>
						    	<%= tweet.user.name %> @<%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %> • <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %><%= tweet.created_at.strftime('%b %e') if Time.now - tweet.created_at > 86400 %>
						    </p>
						    <%= tweet.message.html_safe %>
					  </div>
					</div>
			  </div>
			</div>
			<br>
	  <% end %>
	</div>
</div>
<br>

app/views/epicenter/followers.html.erb
<br>
<h3 class="text-center">@<%= @user.username %>'s Followers</h3>
<br>

<%= render "user_list" %>

<div class="text-center">
	<div class="btn-group">
		<%= link_to "Feed", feed_path, class: "btn btn-primary" %>
		<%= link_to "@#{@user.username}'s Profile", show_user_path(id: @user.id), class: "btn btn-primary" %>
	</div>
</div>
<br>

app/views/epicenter/following.html.erb
<br>
<h3 class="text-center">@<%= @user.username %> is Following</h3>
<br>

<%= render "user_list" %>

<div class="text-center">
	<div class="btn-group">
		<%= link_to "Feed", feed_path, class: "btn btn-primary" %>
		<%= link_to "@#{@user.username}'s Profile", show_user_path(id: @user.id), class: "btn btn-primary" %>
	</div>
</div>
<br>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<br>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<div class="text-center">
			<h1>@<%= @user.username %></h1>
			<br>
			<p><%= image_tag @user.avatar_url(:show), class: "img-thumbnail" %></p>
			<p>Name: <%= @user.name %></p>
			<p>Location: <%= @user.location %></p>
			<p>Bio: <%= @user.bio %></p>
			<p>Number of Tweets: <%= @user.tweets.length %></p>
			<p><%= link_to "Number of Followers: #{@followers}", followers_path(id: @user.id) %></p>
			<p><%= link_to "Number Following: #{@user.following.length}", following_path(id: @user.id) %></p>

			<p>
				<% unless current_user.id == @user.id %>
				  <% if current_user.following.include?(@user.id) %>
				    <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary unfollow-btn" %>
				  <% else %>
				    <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
				  <% end %>
				<% end %>
			</p>
			<h1>@<%= @user.username %>'s Tweets</h1>
		</div>

		<% @user.tweets.each do |tweet| %>
		  <div class="card">
			  <div class="card-body">
			    <h5 class="card-title">
			    	<span><%= image_tag tweet.user.avatar_url(:thumb), class: "img-thumbnail" %></span>
			    	@<%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %>
			    </h5>
			    <p class="card-text"><%= tweet.message.html_safe %></p>
			    <a href="#" class="card-link">Card link</a>
			    <a href="#" class="card-link">Another link</a>
			  </div>
			</div>
			<br>
		<% end %>

		<div class="text-center">
			<div class="btn-group">
				<%= link_to "Feed", feed_path, class: "btn btn-primary" %>
				<%= link_to "Trending", trending_path, class: "btn btn-primary" %>
			</div>
		</div>
		
	</div>
</div>
<br>

app/views/epicenter/tag_tweets.html.erb
<br>
<h1 class="text-center">Messages with <%= @tag.phrase %></h1>
<br>

<div class="row">
  <div class="col-md-3"></div>
	<div class="col-md-6">
    <% @tag.tweets.order(created_at: :desc).each do |tweet| %>
	    <div class="card">
			  <div class="card-body">
			  	<div class="media">
					  <%= image_tag tweet.user.avatar_url(:thumb), class: "rounded-circle", style: "margin-right: 10px" %>
					  <div class="media-body">
						    <p>
						    	<%= tweet.user.name %> @<%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %> • <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %><%= tweet.created_at.strftime('%b %e') if Time.now - tweet.created_at > 86400 %>
						    </p>
						    <%= tweet.message.html_safe %>
					  </div>
					</div>
			  </div>
			</div>
			<br>
    <% end %>
   </div>
</div>
<br>

<div class="text-center">
	<div class="btn-group">
		<%= link_to "Feed", feed_path, class: "btn btn-primary" %>
		<%= link_to "Trending", trending_path, class: "btn btn-primary" %>
	</div>
</div>

<br>

app/views/epicenter/trending.html.erb
<br>
<h3 class="text-center">Top 3 Tweeters</h3>
<br>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Rank</th>
      <th scope="col">Name</th>
      <th scope="col">Handle</th>
      <th scope="col">Total Tweets</th>
    </tr>
  </thead>
  <tbody>
  	<% @tweet_hash.each_with_index do |(key, value), index| %>
	    <tr>
	      <th scope="row"><%= index+1 %></th>
	      <td><%= User.find(key).name %></td>
	      <td>@<%= link_to User.find(key).username, show_user_path(id: User.find(key).id) %></td>
	      <td><%= value %></td>
	    </tr>
    <% end %>
  </tbody>
</table>
<hr>

<br>
<h3 class="text-center">Top 3 Tags</h3>
<br>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Rank</th>
      <th scope="col">Tag</th>
      <th scope="col">Count</th>
    </tr>
  </thead>
  <tbody>
  	<% @tweet_tag_hash.each_with_index do |(key, value), index| %>
	    <tr>
	      <th scope="row"><%= index+1 %></th>
	      <td><%= link_to Tag.find(key).phrase, tag_tweets_path(id: key) %></td>
	      <td><%= value %></td>
	    </tr>
    <% end %>
  </tbody>
</table>
<hr>

<div class="text-center">
	<%= link_to "Feed", feed_path, class: "btn btn-primary" %>
</div>
<br>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialMediaProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>

  <body>

    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Home", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Trending", trending_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Users
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
                <%= link_to "All Users", all_users_path, class: "dropdown-item" %>
                <%= link_to "Following", following_path(id: current_user.id), class: "dropdown-item" %>
                <%= link_to "Followers", followers_path(id: current_user.id), class: "dropdown-item" %>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                @<%= current_user.username %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to 'My Profile', show_user_path(id: current_user.id), class: "dropdown-item" %>
                <%= link_to 'Edit Profile', edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <!-- Navbar End -->

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_area :message, class: "form-control", rows: 4 %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="text-center">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message.html_safe %></td>
        <td><%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<h1 class="text-center">New Tweet</h1>

		<%= render 'form', tweet: @tweet %>

		<br>
		<div class="text-center">
			<%= link_to 'Back', feed_path %>
		</div>
	</div>
</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message.html_safe %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @tweet.user.username, show_user_path(id: @tweet.user_id) %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', feed_path %>